### ISSUE TITLE
Do not send mails via Rails

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1498]
We need a new technical solution for mail sending
 - automated mails
- mails after action

Existing Templates (Admin and Manage) need to be involved in discussion!

Process: 
Admin-Templates are used when a pool is created. From then on, the pool manages it's mail templates on it's own. Changes in the Admin templates are not propagated to the pools.

**Comment by nimaai** [comment]
todo:
- [ ] legacy: mails upon actions
- [ ] legacy: mails at night
- [ ] mail: new columns: `to_address` & `inventory_pool_id`
- [ ] my & reset password feature
- [ ] int-tests irt password reset feature

**Comment by nimaai** [comment]
@nadjaweisskopf when a user or pool gets deleted, should we also delete all emails (sent or not sent yet) of the respective user or inventory pool? archive reasons, etc...?

**Comment by nimaai** [comment]
As discussed with Tom: better to delete the emails together with the user or inventory pool. Also the sent (or failed) emails should be deleted after a certain period (2 weeks? 2 months?)

**Comment by nimaai** [comment]
@nadjaweisskopf to test:
- [ ] reminders
- [ ] all emails
- [ ] passwort reset
- [ ] disabling sending of emails

**Comment by nadjaweisskopf** [comment]
@nimaai 
- Pools are deactivated, not deleted. But that probably doesn't make a difference. 
- As far as I know, a pool can only be deactivated if 
    - all items are retired
    - all items have been taken back
 therefor not mails should be sent anymore by the park and we can delete mails as recommended by @DrTom when deleting users. 
-  So mails can be deleted after 90 days as discussed with @nimaai. That should give us enough time if a user complains he has not received a mail to return his items.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/5b53887e38721bfd232e189e49e1a71691024543

**Comment by urs-van-binsbergen** [comment]
```
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: == 632 AddMoreColumnsToEmails: migrating ======================================
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: -- add_column(:emails, :to_address, :text)
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]:    -> 0.0048s
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: -- add_column(:emails, :inventory_pool_id, :uuid)
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]:    -> 0.0004s
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: -- add_foreign_key(:emails, :inventory_pools, {:name=>:emails_inventory_pool_id_fk, :on_>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]:    -> 0.0115s
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: -- change_column(:emails, :user_id, :uuid, {:null=>true})
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]:    -> 0.0015s
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: -- add_foreign_key(:emails, :users, {:name=>:emails_user_id_fk, :on_delete=>:cascade})
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: rake aborted!
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: StandardError: An error has occurred, this and all later migrations canceled:
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: PG::ForeignKeyViolation: ERROR:  insert or update on table "emails" violates foreign key>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: DETAIL:  Key (user_id)=(4c1996c0-a0b7-5961-8838-e92d07e88382) is not present in table "u>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /leihs/database/db/migrate/632_add_more_columns_to_emails.rb:8:in `up'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: Caused by:
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on ta>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: DETAIL:  Key (user_id)=(4c1996c0-a0b7-5961-8838-e92d07e88382) is not present in table "u>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /leihs/database/db/migrate/632_add_more_columns_to_emails.rb:8:in `up'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: Caused by:
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: PG::ForeignKeyViolation: ERROR:  insert or update on table "emails" violates foreign key>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: DETAIL:  Key (user_id)=(4c1996c0-a0b7-5961-8838-e92d07e88382) is not present in table "u>
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /leihs/database/db/migrate/632_add_more_columns_to_emails.rb:8:in `up'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
Feb 07 13:42:43 zhdk-leihs-staging leihs-migration[2105392]: /home/leihs-database/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
```

**Comment by nadjaweisskopf** [comment]
Tested following mails: 
- Pool-Mail (order received)
- submitted
- approved
- rejected
- aut. pw reset mail with link
- reminder via order list
- mail for order creating by delegation user
- changed mail templates
- deactivated mail sending in admin section and activated mails again

Other tests lending:
- order from new borrow and legacy to two different pools
- accept order
- reject order
- enhance order
- hand out
- contract, value list, picking list
- take back
- adjust take back date
- order with delegation
- availability with entitlement groups

Other tests Admin
- adjusted several Admin settings
- accessed all admin pages
