### ISSUE TITLE
attachments are not saved in admin/categories

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#187]
https://test.leihs-v4.zhdk.ch/procurement/categories

How to reproduce:

1. go to procurement as admin
2. open menu "categories"
3. delete an existing picture of a category
4. add a new picture to a category (no matter if jpg, png, ...)
5. picture is not saved

**Comment by nimaai** [comment]
```
Mar 06 13:56:14 leihs-v4-test ruby[33100]: sh: 1: convert: not found
Mar 06 13:56:14 leihs-v4-test ruby[33100]: RuntimeError (convert: could not create thumbnail):
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/lib/procurement/file_utilities.rb:7:in `convert_file'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:86:in `create_image_with_thumbnail!'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:58:in `block in handle_existing_category'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: activerecord (4.2.7) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: activerecord (4.2.7) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: activerecord (4.2.7) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: activerecord (4.2.7) lib/active_record/transactions.rb:220:in `transaction'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:49:in `handle_existing_category'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:35:in `block in create_or_update_or_destroy'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:32:in `map'
Mar 06 13:56:14 leihs-v4-test ruby[33100]: engines/procurement/app/controllers/procurement/categories_controller.rb:32:in `create_or_update_or_destroy'
```

@drtom Could you please ensure `convert` is available via our ansible recipes?

**Comment by DrTom** [comment]
https://github.com/leihs/leihs_deploy/commit/48073ce0ebc6461612d1a5026980e920f93d8636

**Comment by nimaai** [comment]
Merged to superproject: https://github.com/leihs/leihs/commit/b1b6e67fa37664b603267071aec2138975c1e61b
