### ISSUE TITLE
Send approved notification server log error

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#712]
```
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]: undefined method `locale_name' for nil:NilClass
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mailer/order.rb:4:in `choose_language_for'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mailer/order.rb:8:in `approved'
...
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/notification.rb:31:in `order_approved'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/order.rb:207:in `block in send_approved_notification'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/concerns/log_send_mail_failure.rb:4:in `with_logging_send_mail_failure'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/order.rb:206:in `send_approved_notification'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/order.rb:228:in `approve'
Mar 11 05:30:24 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/controllers/manage/orders_controller.rb:83:in `approve'
```

**Comment by nimaai** [comment]
maybe connected to: https://github.com/leihs/leihs/issues/713

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e0dc31a0b35ba3f0e424aba94763ca676b72b3d1
