### ISSUE TITLE
Send email reminder failure

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#713]
Email von Roger:
```
wir haben heute festgestellt das bei Person X & Person Y keine Erinnerungsmail raus sind.
Beide waren heute bei mir und ich habe manuell ein Erinnerungsmail gesendet, dass nicht angekommen ist.
```

Server log:
```
Mar 11 07:20:23 zhdk-leihs-prod-v5 leihs-legacy[984]: Failed to remind: Person X
Mar 11 07:20:23 zhdk-leihs-prod-v5 leihs-legacy[984]: Couldn't find MailTemplate
Mar 11 07:20:23 zhdk-leihs-prod-v5 leihs-legacy[984]:     /home/leihs-legacy/.rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/core.rb:212:in `find_by!'
Mar 11 07:20:23 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mail_template.rb:94:in `get_template'
Mar 11 07:20:23 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mailer/user.rb:18:in `block (2 levels) in remind'
...
Mar 11 07:20:26 zhdk-leihs-prod-v5 leihs-legacy[984]: Failed to remind: Person Y
Mar 11 07:20:26 zhdk-leihs-prod-v5 leihs-legacy[984]: Couldn't find MailTemplate
Mar 11 07:20:26 zhdk-leihs-prod-v5 leihs-legacy[984]:     /home/leihs-legacy/.rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/core.rb:212:in `find_by!'
Mar 11 07:20:26 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mail_template.rb:94:in `get_template'
Mar 11 07:20:26 zhdk-leihs-prod-v5 leihs-legacy[984]:     /leihs/legacy/app/models/mailer/user.rb:18:in `block (2 levels) in remind'
```

**Comment by nimaai** [comment]
maybe connected to: https://github.com/leihs/leihs/issues/712

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e0dc31a0b35ba3f0e424aba94763ca676b72b3d1
