### ISSUE TITLE
Could not find MailTemplate

### ISSUE THREAD

**Issue by Bekman553** [leihs/leihs#861]
#### Expected behaviour
Ability to edit (or send) mail from inventory pool

#### Actual behaviour
When trying to edit Mail Template inside inventory pool Error Couldn't find MailTemplate appeares. Also mails are not being sent.

When trying to edit mail template this error show in browser:
```
Couldn't find MailTemplate 
leihs Error 404 on localhost:3210 at 2020-07-17T07:02:54.243Z
`/home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/core.rb:212:in `find_by!'
app/controllers/manage/mail_templates_controller.rb:24:in `block (2 levels) in edit'
app/controllers/manage/mail_templates_controller.rb:23:in `each'
app/controllers/manage/mail_templates_controller.rb:23:in `block in edit'
/home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/relation/delegation.rb:38:in `each'`
```
Similar error is showed in logs when mail should be sent:

```
Couldn't find MailTemplate
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/core.rb:212:in `find_by!'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/mail_template.rb:95:in `get_template'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/mailer/order.rb:34:in `block (2 levels) in submitted'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/collector.rb:26:in `custom'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/collector.rb:9:in `text'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/mailer/order.rb:32:in `block in submitted'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/base.rb:900:in `collect_responses'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/base.rb:816:in `mail'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/mailer/order.rb:28:in `submitted'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:188:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:126:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/rescuable.rb:23:in `block in process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/rescuable.rb:22:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionview-5.0.5/lib/action_view/rendering.rb:30:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/base.rb:595:in `block in process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `block in instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/base.rb:594:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/message_delivery.rb:104:in `tap'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionmailer-5.0.5/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/notification.rb:17:in `order_submitted'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/order.rb:214:in `block in send_submitted_notification'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/concerns/log_send_mail_failure.rb:4:in `with_logging_send_mail_failure'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/models/order.rb:213:in `send_submitted_notification'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/controllers/borrow/customer_orders_controller.rb:71:in `block (2 levels) in submit'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/controllers/borrow/customer_orders_controller.rb:33:in `each_pair'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/controllers/borrow/customer_orders_controller.rb:33:in `block in submit'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/transactions.rb:211:in `transaction'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /leihs/legacy/app/controllers/borrow/customer_orders_controller.rb:25:in `submit'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:188:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:126:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/react-rails-2.4.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:382:in `block in make_lambda'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:285:in `block in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:447:in `block in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/audited-342b6b1a9aa5/lib/audited/sweeper.rb:14:in `around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:405:in `public_send'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:405:in `block in make_lambda'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:285:in `block in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:447:in `block in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/bundler/gems/audited-342b6b1a9aa5/lib/audited/sweeper.rb:14:in `around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:405:in `public_send'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:405:in `block in make_lambda'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:285:in `block in halting'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:447:in `block in around'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `block in instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `instrument'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-5.0.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:126:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionview-5.0.5/lib/action_view/rendering.rb:30:in `process'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:190:in `dispatch'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:262:in `dispatch'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:32:in `serve'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:39:in `block in serve'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `each'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `serve'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:727:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/conditional_get.rb:38:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/cookies.rb:613:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:36:in `call_app'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `block in call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:26:in `tagged'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `tagged'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/request_id.rb:24:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.0.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/static.rb:136:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/engine.rb:522:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/railtie.rb:193:in `public_send'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.0.5/lib/rails/railtie.rb:193:in `method_missing'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
Jul 15 16:03:10 leihs leihs-legacy[10789]:     /home/leihs-legacy/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I'm able to edit templates inside admin section.

#### Steps to reproduce
Clean install of Leihs 5.1.10 on Ubuntu 18.04 and Debian 9.12 (two instances tested)

#### Specifications
- Leihs version: 5.1.10
- Browser version: Safari 13.1.1 and Chrome 83.0.4103.116
- MySQL/PostreSQL version:  10.13 (installed via Ansible deployment)

**Comment by Bekman553** [comment]
https://github.com/leihs/leihs/commit/ac6ed618c3867e7f4e3b9b91212ba4bccdc01562
